### ISSUE TITLE
backup_setup.sh references non-existing file

### ISSUE THREAD

**Issue by skafdan** [skafdan/ChatServer-Deployment#12]
![image](https://user-images.githubusercontent.com/40788343/135164320-60a8dc11-801a-466c-a3d9-bb40f34aaad9.png)

**Comment by skafdan** [comment]
Created branch credentials to address this

**Comment by hmcalister** [comment]
Perfect, exactly what needs to occur for depolyment and documented. Solves bug as much as possible while explaining why we can't give out secret keys
