### ISSUE TITLE
Password not hashed.

### ISSUE THREAD

**Issue by skafdan** [skafdan/ChatServer-Deployment#5]
Password currently store in plain text
![image](https://user-images.githubusercontent.com/40788343/134606907-5be33ac8-de13-4614-9a48-2ce8ca646f32.png)

passwd column in user table needs to store hash of sha256(password+salt)

**Comment by hmcalister** [comment]
Excellent point, didn't actually implement any hashing haha
Easy fix, will do now
To confirm, you want passwd to store SHA256(plaintext + salt) right?

**Comment by skafdan** [comment]
@Gamma749 
Ah ok perfect. Lets just leave it for now I will make a pull request for the website branch on monday and we can have a branch entirely for it.

**Comment by hmcalister** [comment]
Oh I mean it was a one line fix, I can commit the change now if you'd like
But we can make a new branch later
![image](https://user-images.githubusercontent.com/39180428/134607742-73bba9bf-b991-4338-87f3-6b50fbc95cc9.png)

**Comment by skafdan** [comment]
I think it best to have it its own branch in case we get it any bugs or we need to test it.

**Comment by skafdan** [comment]
closed by merge pull request  b633fa8
